title: Rebekah Coley
author: GitHub User
email: coleyrebekah@gmail.com
description: I am a postgraduate with a masters degree in molecular biology, and have recently completed Generation UK’s Junior Data Engineering program. 
I am enthusiastic to apply my newly acquired technical skills and previous transferable skills to a junior data engineer role.
  
# social links
linkedin_username: Rebekah Coley # DO NOT include the @ character, or else the build will fail!
github_username: rebekahcoley-programs # DO NOT include the @ character, or else the build will fail!
instagram_username: rebekahcoley_94

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
